version: '3.3'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - mysql
      - redis
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: laravelpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6380:6379"
    networks:
      - laravel-network

  laravel_echo_server:
    image: node:18-alpine
    container_name: laravel_echo_server
    working_dir: /app
    volumes:
      - ./docker/laravel-echo-server:/app
    command: sh -c "npm install && npx laravel-echo-server start"
    ports:
      - "6001:6001"
    depends_on:
      - redis
    networks:
      - laravel-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: laravel_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  mysql_data:
